"""empty message

Revision ID: 0b4b5825406e
Revises: 
Create Date: 2025-03-10 15:06:50.714765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4b5825406e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
