"""empty message

Revision ID: 20ea4067ec1d
Revises: adac54386233
Create Date: 2025-03-11 11:14:31.384400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ea4067ec1d'
down_revision = 'adac54386233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
