"""Add framework_id to safeguards

Revision ID: 2cd0ba7c5ac4
Revises: 4f19d3d77c0c
Create Date: 2025-03-12 14:58:19.580346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd0ba7c5ac4'
down_revision = '4f19d3d77c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safeguards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('framework_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_safeguards_framework_id', 'control_frameworks', ['framework_id'], ['id'])
    
    # Set a default framework_id for existing rows (assuming 1 is a valid framework_id)
    op.execute('UPDATE safeguards SET framework_id = 1 WHERE framework_id IS NULL')
    
    # Alter the column to be non-nullable
    with op.batch_alter_table('safeguards', schema=None) as batch_op:
        batch_op.alter_column('framework_id', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safeguards', schema=None) as batch_op:
        batch_op.drop_constraint('fk_safeguards_framework_id', type_='foreignkey')
        batch_op.drop_column('framework_id')
    # ### end Alembic commands ###
