"""empty message

Revision ID: 40573e4f5f28
Revises: 458042c41daf
Create Date: 2025-03-11 11:44:22.179758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40573e4f5f28'
down_revision = '458042c41daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
