"""Add framework_id to implementation_groups

Revision ID: 4f19d3d77c0c
Revises: 7193e2eaa963
Create Date: 2025-03-11 14:58:19.580346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f19d3d77c0c'
down_revision = '7193e2eaa963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('implementation_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('framework_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_implementation_groups_framework_id', 'control_frameworks', ['framework_id'], ['id'])
    
    # Set a default framework_id for existing rows (assuming 1 is a valid framework_id)
    op.execute('UPDATE implementation_groups SET framework_id = 1 WHERE framework_id IS NULL')
    
    # Alter the column to be non-nullable
    with op.batch_alter_table('implementation_groups', schema=None) as batch_op:
        batch_op.alter_column('framework_id', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('implementation_groups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_implementation_groups_framework_id', type_='foreignkey')
        batch_op.drop_column('framework_id')
    # ### end Alembic commands ###
