"""empty message

Revision ID: 60b6cfeb33b7
Revises: 68a17f64427e
Create Date: 2025-03-11 11:24:20.298922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b6cfeb33b7'
down_revision = '68a17f64427e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
