"""empty message

Revision ID: 68a17f64427e
Revises: 20ea4067ec1d
Create Date: 2025-03-11 11:18:37.197357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a17f64427e'
down_revision = '20ea4067ec1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
