"""empty message

Revision ID: 7193e2eaa963
Revises: e0df7f5add5b
Create Date: 2025-03-11 13:20:19.928461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7193e2eaa963'
down_revision = 'e0df7f5add5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
