"""empty message

Revision ID: 758f8149358f
Revises: 0b4b5825406e
Create Date: 2025-03-10 15:16:03.287038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758f8149358f'
down_revision = '0b4b5825406e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
