"""Create implementation_groups table

Revision ID: 9ca1126c2fd7
Revises: 853bfd4ad565
Create Date: 2025-03-11 10:35:23.836976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca1126c2fd7'
down_revision = '853bfd4ad565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
