"""Add number field to control_frameworks table

Revision ID: adac54386233
Revises: 872c2fd3050a
Create Date: 2025-03-11 11:07:21.349471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adac54386233'
down_revision = '872c2fd3050a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_frameworks', sa.Column('number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_frameworks', 'number')
    # ### end Alembic commands ###
