"""empty message

Revision ID: e0df7f5add5b
Revises: 40573e4f5f28
Create Date: 2025-03-11 13:09:28.540948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0df7f5add5b'
down_revision = '40573e4f5f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
