"""empty message

Revision ID: fa218871b9e9
Revises: 
Create Date: 2025-03-07 11:27:35.319726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa218871b9e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
